const app=document.getElementById('app');
const S={p:Number(localStorage.getItem('a0212_p')||0),final:localStorage.getItem('a0212_final')==='1'};
function shell(x){return '<div class="shell"><div class="topbar"><span>ARCHIVO 0212</span><span class="status">CONEXIÓN ESTABLE</span></div><main class="content"><section class="panel">'+x+'</section></main></div>'}
function btn(t,a){return '<button class="btn" data-a="'+a+'">'+t+'</button>'}
function choice(t,s,a){return '<button class="choice" data-a="'+a+'">'+t+'<small>'+s+'</small></button>'}
function save(){localStorage.setItem('a0212_p',S.p)}
function intro(){app.innerHTML=shell('<div class="system">CONEXIÓN ESTABLECIDA<br>RECUPERANDO ARCHIVO...<br>████████████████ 100%</div><h1 class="title">ARCHIVO 0212</h1><div class="system">ESTADO: INCOMPLETO</div><div class="message" style="margin-top:38px"><p>Hay alguien intentando abrir este archivo.</p><p>Identidad no reconocida.</p><p>Pero el archivo parece reconocerte.</p></div>'+btn('CONTINUAR','f1'))}
function f1(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 01 // REGISTRO</div><h1 class="title">Algo no cuadra.</h1><div class="message"><p>El archivo perdió una parte de su registro.</p><p>Solo quedaron los datos necesarios para reconstruirlo.</p></div><div class="file" style="margin-top:24px"><div class="filebar"><span>REGISTRO_01.DAT</span><span>PARCIAL</span></div><div class="filebody">INICIO DE RECUPERACIÓN   17:30</div><div style="padding:0 25px 25px;font:13px/1.9 'JetBrains Mono',monospace;color:#c8c8d0">BLOQUES RECUPERADOS    6<br>TIEMPO POR BLOQUE       12 MINUTOS<br><br>El siguiente registro apareció justo después de recuperar todos los bloques.<br><br><span style="color:#85858f">¿A qué hora apareció?</span><div style="display:flex;gap:8px;margin-top:16px"><input id="time1" inputmode="numeric" maxlength="5" placeholder="HH:MM" style="flex:1;min-width:0;background:#09090c;border:1px solid var(--line);color:white;padding:12px;font:13px 'JetBrains Mono',monospace"><button class="btn" data-a="solve1" style="margin-top:0">COMPROBAR</button></div><div id="err1"></div></div></div>')}

function f2(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 02 // LA HORA</div><h1 class="title">18:42</h1><div class="message"><p>A las 18:42 ocurrió algo.</p></div><div class="grid" style="margin-top:24px">'+choice('LEER','16:20','wrong')+choice('ESCRIBIR','19:10','wrong')+choice('ESCUCHAR','18:42','audio')+choice('DORMIR','23:51','wrong')+'</div>')}
function audio(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 03 // TRANSMISIÓN</div><h1 class="title">Señal recuperada.</h1><div class="message"><p>Hay algo que no dije.</p><p>Escucha nuevamente.</p></div><div class="audio"><div class="audiohead"><span>ARCHIVO // TRANSMISIÓN 03</span><span id="ast">EN ESPERA</span></div><div class="label">VOZ</div><canvas id="voice"></canvas><div class="label">SEÑAL / AMBIENTE</div><canvas id="music"></canvas><div class="progress" id="prog"><i></i></div><div class="time"><span id="cur">00:00</span><span id="dur">--:--</span></div><div class="controls"><button class="icon" data-play>▶</button><button class="icon" data-repeat>↻</button></div><audio id="aud" preload="metadata" src="assets/audio/transmission-03.mp3"></audio></div>') ; audioSetup()}
function f4(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 04 // TRANSCRIPCIÓN</div><h1 class="title">Donde nadie mira.</h1><div class="file"><div class="filebar"><span>TRANSMISIÓN_03.TXT</span><span>RECUPERADA</span></div><div class="filebody">00:12 — "No sabía si hacerlo."\n\n00:19 — "Tal vez era demasiado tarde."\n\n00:27 — "Pero todavía quedaba algo."\n\n00:37 — [ SONIDO ]\n\n00:44 — "Así que lo dejé donde nadie mira."</div></div><div class="message" style="margin-top:22px"><p>Si alguien quisiera esconder algo sin que pareciera escondido...</p></div><div class="desktop"><div class="folder" data-a="f5"><div class="foldershape"></div>PAPELERA</div></div>')}
function f5(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 05 // ARCHIVO ELIMINADO</div><h1 class="title">nota_final.txt</h1><div class="file"><div class="filebar"><span>NOTA_FINAL.TXT</span><span>RECUPERADA</span></div><div class="filebody">Hay una cosa que siempre hacemos cuando queremos recordar algo.\n\nEscribirlo.\n\nPero yo hice algo diferente.\n\n12\n02\n\nTodavía no.\n\nNo leas los números.\nMira dónde están.</div></div><div class="message" style="margin-top:22px"><p>El archivo conserva un año: <strong>2008</strong>.</p></div>'+btn('IDENTIFICAR FECHA','f6'))}
function f6(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 06 // CONEXIÓN</div><h1 class="title">Relaciona lo que ya tienes.</h1><div class="data"><span>18:42</span><span>ESCUCHAR</span></div><div class="data"><span>03</span><span>TRES GOLPES</span></div><div class="data"><span>12/02/2008</span><span>FECHA</span></div><div class="message" style="margin-top:24px"><p>No busques otro dato.</p><p>¿Qué ocurre el 12/02/2008?</p></div><div class="grid">'+choice('UNA FECHA CUALQUIERA','','wrong')+choice('MI CUMPLEAÑOS','','f7')+choice('EL FINAL DEL ARCHIVO','','wrong')+'</div>')}
function f7(){app.innerHTML=shell('<div class="kicker">FRAGMENTO 07 // IDENTIDAD</div><h1 class="title">Coincidencia encontrada.</h1><div class="system" style="margin:25px 0">ANALIZANDO DATOS...<br><br>18:42<br>03<br>12/02/2008<br><br>COMPARANDO...<br>██████████████████ 100%</div><div class="filebody" style="border:1px solid var(--line)">DESTINATARIA:\n\nC H A R L O T T E</div><div class="message" style="margin-top:22px"><p>Ahora entiendes por qué el archivo se llamaba 0212.</p></div>'+btn('CONTINUAR','reveal'))}
function reveal(){app.innerHTML=shell('<div class="kicker">IDENTIDAD DEL CREADOR</div><h1 class="title">LUIS</h1><div class="message"><p>Y supongo...</p><p>que ya sabes quién estuvo hablando contigo todo este tiempo.</p><p>Quién dejó las pistas.</p><p>Quién preparó este archivo.</p><p>Fui yo.</p><p>Luis.</p></div>'+btn('ABRIR ARCHIVO','desk'))}
function desk(){app.innerHTML=shell('<div class="kicker">ARCHIVO 0212 // ESCRITORIO</div><div class="desktop" style="margin-top:25px"><div class="folder" data-a="folder"><div class="foldershape"></div>PARA CHARLOTTE</div></div>')}
function folder(){app.innerHTML=shell('<div class="kicker">PARA CHARLOTTE</div><h1 class="title">Sin pistas.</h1><div class="file"><div class="filebar"><span>mensaje_final.txt</span><span>ABIERTO</span></div><div class="filebody">Si llegaste hasta aquí...\n\nAquí irá el mensaje personal que quiero dejarte.\n\nNo había ningún misterio que resolver.\nSolo quería encontrar una forma diferente de llegar hasta ti.\n\n— Luis</div></div>'+btn('CONTINUAR','pass'))}
function pass(){app.innerHTML=shell('<div class="kicker">ARCHIVO PROTEGIDO</div><h1 class="title">Último archivo.</h1><div class="lock"><div class="system">🔒 Este archivo requiere una contraseña.</div><div class="message" style="margin-top:18px"><p>La contraseña no es la fecha de quien recibió el archivo.</p><p>Encuentra la fecha de quien estuvo al otro lado.</p></div><div class="password"><input id="pw" inputmode="numeric" placeholder="DD/MM/AAAA"><button class="btn" data-a="unlock">DESBLOQUEAR</button></div><div id="err"></div></div>')}
function heart(){app.innerHTML=shell('<div class="heartwrap"><div class="kicker">IDENTIDAD CONFIRMADA</div><div class="heartstage"><svg viewBox="0 0 500 500"><g opacity=".12"><path d="M250 30V470M30 250H470" stroke="#888"/><circle cx="250" cy="250" r="175" fill="none" stroke="#888" stroke-dasharray="2 8"/></g><path id="hp" class="heartpath" d="M250 395 C215 355 100 285 100 175 C100 110 180 85 250 150 C320 85 400 110 400 175 C400 285 285 355 250 395 Z"/><circle id="hd" class="heartdot" r="4" cx="100" cy="175"/><text class="heartname" x="250" y="250" text-anchor="middle">CHARLOTTE</text></svg></div><div class="system">ARCHIVO 0212</div></div>');animateHeart()}
function audioSetup(){const a=document.getElementById('aud'),v=document.getElementById('voice'),m=document.getElementById('music'),vc=v.getContext('2d'),mc=m.getContext('2d');let ac,an,d,raf;function size(){[v,m].forEach(c=>{c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio})}size();addEventListener('resize',size);function draw(){vc.clearRect(0,0,v.width,v.height);mc.clearRect(0,0,m.width,m.height);if(an&&d){an.getByteTimeDomainData(d);vc.strokeStyle='#9a82ff';vc.beginPath();for(let i=0;i<d.length;i++){let x=i*v.width/d.length,y=v.height/2+(d[i]-128)/128*v.height*.4;i?vc.lineTo(x,y):vc.moveTo(x,y)}vc.stroke();an.getByteFrequencyData(d);mc.fillStyle='rgba(154,130,255,.45)';for(let i=0;i<40;i++){let h=d[i]/255*m.height*.8;mc.fillRect(i*m.width/40,m.height-h,m.width/45,h)}}else{vc.strokeStyle='#25252e';vc.beginPath();vc.moveTo(0,v.height/2);vc.lineTo(v.width,v.height/2);vc.stroke();}raf=requestAnimationFrame(draw)}draw();document.querySelector('[data-play]').onclick=async()=>{if(!ac){ac=new AudioContext();const src=ac.createMediaElementSource(a);an=ac.createAnalyser();an.fftSize=256;d=new Uint8Array(an.frequencyBinCount);src.connect(an);an.connect(ac.destination)}if(ac.state==='suspended')await ac.resume();if(a.paused){a.play();document.getElementById('ast').textContent='TRANSMISIÓN ACTIVA'}else{a.pause();document.getElementById('ast').textContent='PAUSADA'}};document.querySelector('[data-repeat]').onclick=()=>{a.currentTime=0;a.play()};a.onloadedmetadata=()=>document.getElementById('dur').textContent=fmt(a.duration);a.ontimeupdate=()=>{document.getElementById('cur').textContent=fmt(a.currentTime);document.querySelector('.progress i').style.width=(a.currentTime/a.duration*100)+'%'};document.getElementById('prog').onclick=e=>{a.currentTime=e.offsetX/e.currentTarget.clientWidth*a.duration};a.onended=()=>{document.getElementById('ast').textContent='TRANSMISIÓN FINALIZADA ✓';S.p=4;save();setTimeout(f4,800)}}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')}
function animateHeart(){const p=document.getElementById('hp'),d=document.getElementById('hd'),len=p.getTotalLength(),start=performance.now();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;function f(t){let k=Math.min(1,(t-start)/4800),e=1-Math.pow(1-k,3);p.style.strokeDashoffset=len*(1-e);let q=p.getPointAtLength(len*e);d.setAttribute('cx',q.x);d.setAttribute('cy',q.y);if(k<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
document.addEventListener('click',e=>{const x=e.target.closest('[data-a]');if(!x)return;const a=x.dataset.a;if(a==='f1'){S.p=1;save();f1()}else if(a==='book'){S.p=1;save();f2()}else if(a==='solve1'){const v=document.getElementById('time1').value.trim();if(v==='18:42'){S.p=2;save();f2()}else{document.getElementById('err1').innerHTML='<div class="error">EL REGISTRO NO COINCIDE</div>';document.getElementById('time1').animate([{transform:'translateX(0)'},{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],180)}}else if(a==='audio'){S.p=3;save();audio()}else if(a==='wrong'){x.animate([{transform:'translateX(0)'},{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],180)}else if(a==='f5'){S.p=4;save();f5()}else if(a==='f6'){S.p=5;save();f6()}else if(a==='f7'){S.p=6;save();f7()}else if(a==='reveal')reveal();else if(a==='desk')desk();else if(a==='folder')folder();else if(a==='pass')pass();else if(a==='unlock'){if(document.getElementById('pw').value.trim()==='11/06/2006'){S.final=true;localStorage.setItem('a0212_final','1');heart()}else document.getElementById('err').innerHTML='<div class="error">CONTRASEÑA INCORRECTA</div>'}});
if(S.final)heart();else if(S.p===0)intro();else if(S.p===1)f1();else if(S.p===2)f2();else if(S.p===3)audio();else if(S.p===4)f4();else if(S.p===5)f5();else if(S.p===6)f6();else f7();
